version: '3.8'

services:
  naming-server:
    build:
      context: ./naming-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "sleep 2"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


  security-service:
    build:
      context: ./security-service
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: security-db
      MYSQL_USER: root
      #      MYSQL_PASSWORD: root
      MYSQL_DATABASE: security
      MYSQL_PORT: 3306
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka/"

    networks:
      - my-network
    depends_on:
      naming-server:
        condition: service_healthy
      security-db:
        condition: service_healthy


  messages-service:
    build:
      context: ./messages-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka/"
    networks:
      - my-network
    depends_on:
      naming-server:
        condition: service_healthy

  security-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: security
      #      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql_security
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 0s



  phymyadmin:
    image: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: security-db
      MYSQL_ROOT_PASSWORD:
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge