version: '3.8'
services:
  naming-server:
    build:
      context: ./naming-server
    ports:
      - "8761:8761"
    networks:
      - my-network


  security-service:
    build:
      context: ./security-service
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: security-db
      MYSQL_USER: root
      #      MYSQL_PASSWORD: root
      MYSQL_DATABASE: security
      MYSQL_PORT: 3306
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka/"

    networks:
      - my-network
    depends_on:
      - naming-server
      - security-db


  content-service:
    build:
      context: ./content-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka/"
      MYSQL_HOST: content-db
      MYSQL_USER: root
      #      - MYSQL_PASSWORD=root
      MYSQL_DATABASE: profiles
      MYSQL_PORT: 3305
      EUREKA_HOST: naming-server
      EUREKA_PORT: 8761

    depends_on:
      - naming-server
      - content-db
      - security-service
    networks:
      - my-network






  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka/"
    networks:
      - my-network
    depends_on:
      - naming-server



  messages-service:
    build:
      context: ./messages-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka/"
    networks:
      - my-network
    depends_on:
      - naming-server
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://naming-server:8761/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  security-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: security
      #      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql_security

  content-db:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: profiles
        #      MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      ports:
        - "3306:3305"
      networks:
        - my-network
      volumes:
        - content_data:/var/lib/mysql_content

  phymyadmin:
    image: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: content-db
      MYSQL_ROOT_PASSWORD:
    networks:
      - my-network

volumes:
  mysql_data:
  content_data:

networks:
  my-network:
    driver: bridge
